version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
      - .env-dev-values
    command: bundle exec ruby get-this.rb  -o 0.0.0.0

  css:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec ruby ./config/css-listener.rb

  js:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec ruby ./config/js-listener.rb

volumes:
  gem_cache:
