version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env
      - .env-dev-values
    command:
      - bundle 
      - exec 
      - rackup 
      - -p
      - "4567"
      - --host
      - 0.0.0.0

  css:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec ruby ./config/css-listener.rb

  js:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec ruby ./config/js-listener.rb

volumes:
  gem_cache:
