#Labels for dropdown list of pickup locations
AAEL: Art, Architecture, & Engineering Library
DHCL: Donald Hall Collection
FINE: Fine Arts
MUSM: Museums
MUSIC: Music Library
SHAP: Shapiro Undergraduate Library
TAUB: Taubman Health Sciences
FLINT: "Thompson Library (UM-Flint)"
DBRN: "Mardigian Library (UM-Dearborn)"
