name: Build latest from main and AutoDeploy to Testing and Staging

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ 'main' ]
    types: [ completed ]

env:
  IMAGE_NAME: get-this-unstable

jobs:
  build-unstable:
    name: Build unstable ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.sha }}
    secrets: inherit

  deploy-testing:
    needs: build-unstable
    name: Deploy to ${{ github.event.inputs.tanka_env }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}-unstable:${{ github.event.inputs.tag }}
      file: environments/get-this/testing/web-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit
