name: Build and Deploy Production

on:
  release:
    types: [ released ]

env:
  TAG: ${{ github.event.release.tag_name }}
  IMAGE_NAME: get-this

jobs:
  build:
    name: Build ${{ env.TAG }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.prod
        secrets: |
          "gh_package_read_token=${{ secrets.GH_PACKAGE_READ_TOKEN }}"
        push: true
        tags: | 
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Generate app token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.SEARCH_CONFIG_REPO_RW_APP_ID }}
        installation_id: ${{ secrets.SEARCH_CONFIG_REPO_RW_INSTALL_ID }}
        private_key: ${{ secrets.SEARCH_CONFIG_REPO_RW_KEY }}
    - name: Set message
      id: set_message
      run: |
        echo "TITLE=Update get-this/production to ${{ env.TAG }}" >> $GITHUB_OUTPUT 
        echo "DESCRIPTION=Originating repository is ${{ github.repository }}\nRun ID is $GITHUB_RUN_ID\nUser is ${{ github.actor }}" >> $GITHUB_OUTPUT
    - name: Set Payload
      run: |
        data=$(echo '[
          { 
            "environment": "get-this/production", 
            "key": "web", 
            "image": "ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ env.TAG }}" 
          }
        ]' | python -c 'import json, sys;var=json.dumps(json.load(sys.stdin));print(json.dumps(var))' )
        echo "PAYLOAD={\"title\": \"${{ steps.set_message.outputs.TITLE }}\",\"description\": \"${{ steps.set_message.outputs.DESCRIPTION }}\", \"data\": $data }" >> $GITHUB_ENV
    - name: echo payload
      run: echo $PAYLOAD
    - name: Send the message
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: update-image
        token: ${{ steps.generate_token.outputs.token }}
        repository: mlibrary/search-kube
        client-payload: ${{ env.PAYLOAD }}
