name: Manual Deploy Unstable

on:
  workflow_dispatch:
    inputs:
      tanka_env:
        description: 'tanka environment'
        required: true
        type: choice
        default: "get-this/testing"
        options:
          - "get-this/testing"
          - "get-this/staging"
      tag:
        description: tag
        required: true

env:
  IMAGE_NAME: get-this-unstable

jobs:
  deploy-unstable:
    name: Deploy ${{ github.event.inputs.tag }} to ${{ github.event.inputs.tanka_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone latest repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check that the tag exists in repo
      id: tag_check
      run: |
        if git rev-parse 'refs/tags/${{ github.event.inputs.tag }}' &> /dev/null; then
          echo 'tag=${{ github.event.inputs.tag }}' >> $GITHUB_OUTPUT
        elif git rev-parse '${{ github.event.inputs.tag }}' &> /dev/null; then
          echo "tag=`git rev-parse '${{ github.event.inputs.tag }}'`" >> $GITHUB_OUTPUT
        else
          echo "Couldn't figure out tag from input: ${{ github.event.inputs.tag }}"
          echo "Aborting deployment."
          false
        fi
    - name: Log into Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check that the tag exists in container registry
      id: image_check
      run: |
        if docker manifest inspect ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ steps.tag_check.outputs.tag }} > /dev/null; then
          echo 'image_exists=true' >> $GITHUB_OUTPUT
          echo "image exists!"
        else
          echo "image doesn't exist; Starting to Build and push image"
        fi
    - name: Checkout Correct repository
      if: ${{ steps.image_check.outputs.image_exists != 'true' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Build and Push
      if: ${{ steps.image_check.outputs.image_exists != 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        secrets: |
          "gh_package_read_token=${{ secrets.GH_PACKAGE_READ_TOKEN }}"
        push: true
        tags: ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{steps.tag_check.outputs.tag}}
    - name: Generate app token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.SEARCH_CONFIG_REPO_RW_APP_ID }}
        installation_id: ${{ secrets.SEARCH_CONFIG_REPO_RW_INSTALL_ID }}
        private_key: ${{ secrets.SEARCH_CONFIG_REPO_RW_KEY }}
    - name: Set message
      id: set_message
      run: |
        echo "TITLE=Update ${{ github.event.inputs.tanka_env }} to ${{ steps.tag_check.outputs.tag }}" >> $GITHUB_OUTPUT 
        echo "DESCRIPTION=Originating repository is ${{ github.repository }}\nRun ID is $GITHUB_RUN_ID\nUser is ${{ github.actor }}" >> $GITHUB_OUTPUT
    - name: Set PAYLOAD
      run: |
        data=$(echo '[
          { 
            "environment": "${{ github.event.inputs.tanka_env }}", 
            "key": "web", 
            "image": "ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ steps.tag_check.outputs.tag }}" 
          }
        ]' | python -c 'import json, sys;var=json.dumps(json.load(sys.stdin));print(json.dumps(var))' )
        echo "PAYLOAD={\"title\": \"${{ steps.set_message.outputs.TITLE }}\",\"description\": \"${{ steps.set_message.outputs.DESCRIPTION }}\", \"data\": $data }" >> $GITHUB_ENV
    - name: echo payload
      run: echo $PAYLOAD
    - name: Send the message
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: update-image
        token: ${{ steps.generate_token.outputs.token }}
        repository: mlibrary/search-kube
        client-payload: ${{ env.PAYLOAD }}
